// Generated by CoffeeScript 1.10.0
(function() {
  var path, transformTools;

  path = require('path');

  transformTools = require('browserify-transform-tools');

  module.exports = transformTools.makeStringTransform('txtify', {
    excludeExtensions: ['.ts', '.js']
  }, function(content, opts, done) {
    var ext, regex, result;
    regex = /(\..+)$/gm;
    ext = regex.exec(opts.file)[1];
    if (opts.config.extensions.indexOf(ext) >= 0) {
      result = null;
      if (ext === ".json") {
        content = JSON.parse(content);
      }
      if (content !== null) {
        result = "module.exports = " + (JSON.stringify(content));
      }
    }
    return done(null, result);
  });

}).call(this);
